
const Constants = {
  MIN_DELAY_BETWEEN_INFINITE_LIST_FETCH: 400,
  MAX_DELAY_BETWEEN_INFINITE_LIST_FETCH: 2000,
  INFINITE_LIST_FETCH_COUNT: 5,
  MAX_POST_CHARACTERS: 180
};

export default Constants;